post_install_script = '''
#!/bin/bash -e
# Script based on the RPM %systemd_post scriptlet. See:
#   - https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#_systemd
#   - https://github.com/systemd/systemd/blob/main/src/rpm/macros.systemd.in
#   - https://github.com/systemd/systemd/blob/main/src/rpm/systemd-update-helper.in
if [ $EUID -ne 0 ]; then
    echo >&2 "ERROR: postinst script must be run as root"
    exit 1
fi

if [ $1 -eq 1 ] ; then
    # Initial installation
    R_USER=my_test
    R_GROUP=${R_USER}
    R_HOME_DIR=/var/lib/${R_USER}
    R_HOME_DIR_PERMS=700

    # https://github.com/NLnetLabs/routinator/issues/774
    if ! id ${R_USER} > /dev/null 2>&1; then
        # According to the CentOS 7 useradd man page:
        # --user-group causes a group by the same name as the user to be created
        # --create-home should force creation of a home dir even for a system account.
        useradd --home-dir ${R_HOME_DIR} --system --create-home --user-group ${R_USER}
    fi

    # Ensure that the home directory has the correct ownership
    chown -R ${R_USER}:${R_GROUP} ${R_HOME_DIR}

    # Ensure that the home directory has the correct permissions
    chmod ${R_HOME_DIR_PERMS} ${R_HOME_DIR}
    
    systemctl --no-reload preset "mytest.timer"
fi
'''

pre_uninstall_script = '''
#!/bin/bash -e
# Script based on the RPM %systemd_preun scriptlet. See:
#   - https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#_systemd
#   - https://github.com/systemd/systemd/blob/main/src/rpm/macros.systemd.in
#   - https://github.com/systemd/systemd/blob/main/src/rpm/systemd-update-helper.in
if [ $1 -eq 0 ] ; then
    # Package removal, not upgrade
        if [ -d /run/systemd/system ]; then
            systemctl --no-reload disable --now "mytest.timer"
        else
            systemctl --no-reload disable "mytest.timer"
        fifi
'''

post_uninstall_script = '''
#!/bin/bash -e
# Script based on the RPM %systemd_postun scriptlet. See:
#   - https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#_systemd
#   - https://github.com/systemd/systemd/blob/main/src/rpm/macros.systemd.in
#   - https://github.com/systemd/systemd/blob/main/src/rpm/systemd-update-helper.in
systemctl daemon-reload >/dev/null 2>&1 || :
if [ $1 -ge 1 ] ; then
    systemctl try-restart mytest.timer >/dev/null 2>&1 || :
fi
'''