name: Packaging

on:
  push:

  workflow_dispatch:

  schedule:
    - cron: '0 0 * * 0'

# TODO: Use a matrix here for the different permutations of settings to invoke the reusable workflow with?

jobs:
  default_tests_with_upgrades:
    uses: NLnetLabs/ploutos/.github/workflows/pkg-rust.yml@support-testing-in-other-images
    secrets: inherit
    with:
      artifact_prefix: default_tests_with_upgrades_

      package_build_rules: |
        pkg:
          - "mytest"
        image:
          - "ubuntu:bionic"
          - "ubuntu:jammy"
          - "debian:buster"
          - "rockylinux:8"
        mode:
          - "fresh-install"
        target:
          - "x86_64"
        test-image:
          - ""
        include:
          - pkg: "mytest"
            image: "ubuntu:jammy"
            target: "x86_64"
            mode: "upgrade-from-published"

          - pkg: "mytest"
            image: "rockylinux:8"
            systemd_service_unit_file: "pkg/common/mytest.mytest.*"
            target: "x86_64"
            mode: "fresh-install"

          - pkg: "mytest"
            image: "rockylinux:8"
            systemd_service_unit_file: "pkg/common/mytest.mytest.*"
            target: "x86_64"
            mode: "upgrade-from-published"

          - pkg: "mytest"
            image: "rockylinux:8"
            target: "x86_64"
            test-image: "almalinux/8"

          - pkg: "mytest"
            image: "rockylinux:8"
            target: "x86_64"
            test-image: "centos/9-Stream"

      package_test_scripts_path: pkg/test-scripts/test-<package>.sh

      deb_extra_build_packages: libssl-dev
      deb_apt_key_url: 'https://raw.githubusercontent.com/NLnetLabs/ploutos-testing/main/repo/apt-key.asc'
      deb_apt_source: 'deb https://raw.githubusercontent.com/NLnetLabs/ploutos-testing/main/repo/linux/${OS_NAME}/ ${OS_REL} main'

      rpm_scriptlets_path: pkg/rpm/scriptlets.toml
      rpm_yum_key_url: 'https://raw.githubusercontent.com/NLnetLabs/ploutos-testing/main/repo/yum-key.asc'
      rpm_yum_repo: |
        [nlnetlabs]
        name=NLnet Labs
        baseurl=https://raw.githubusercontent.com/NLnetLabs/ploutos-testing/main/repo/linux/centos/$releasever/main/$basearch
        enabled=1
