name: Packaging

on:
  push:
  workflow_dispatch:

# TODO: Use a matrix here for the different permutations of settings to invoke the reusable workflow with?

jobs:
  full:
    uses: NLnetLabs/.github/.github/workflows/pkg-rust.yml@v1.1.0
    secrets: inherit
    with:
      docker_org: ximoneighteen
      docker_repo: ximontest

      cross_build_rules_path: pkg/rules/cross-build-rules.yml
      docker_build_rules_path: pkg/rules/docker-build-rules.yml
      package_build_rules_path: pkg/rules/package-build-rules.yml
      package_test_rules_path: pkg/rules/package-test-rules.yml
      package_test_scripts_path: pkg/test-scripts/test-<package>.sh

      cross_build_args: --no-default-features
      deb_extra_build_packages: libssl-dev
      deb_maintainer: The NLnet Labs RPKI Team <rpki@nlnetlabs.nl>
      rpm_scriptlets_path: pkg/rpm/scriptlets.toml

  minimal:
    uses: NLnetLabs/.github/.github/workflows/pkg-rust.yml@v1.1.0

  no_test_scripts:
    uses: NLnetLabs/.github/.github/workflows/pkg-rust.yml@v1.1.0
    secrets: inherit
    with:
      docker_org: ximoneighteen
      docker_repo: ximontest

      cross_build_rules_path: pkg/rules/cross-build-rules.yml
      docker_build_rules_path: pkg/rules/docker-build-rules.yml
      package_build_rules_path: pkg/rules/package-build-rules.yml
      package_test_rules_path: pkg/rules/package-test-rules.yml

      cross_build_args: --no-default-features
      deb_extra_build_packages: libssl-dev
      deb_maintainer: The NLnet Labs RPKI Team <rpki@nlnetlabs.nl>
      rpm_scriptlets_path: pkg/rpm/scriptlets.toml

  no_tests:
    uses: NLnetLabs/.github/.github/workflows/pkg-rust.yml@v1.1.0
    secrets: inherit
    with:
      docker_org: ximoneighteen
      docker_repo: ximontest

      cross_build_rules_path: pkg/rules/cross-build-rules.yml
      docker_build_rules_path: pkg/rules/docker-build-rules.yml
      package_build_rules_path: pkg/rules/package-build-rules.yml
      package_test_scripts_path: pkg/test-scripts/test-<package>.sh

      cross_build_args: --no-default-features
      deb_extra_build_packages: libssl-dev
      deb_maintainer: The NLnet Labs RPKI Team <rpki@nlnetlabs.nl>
      rpm_scriptlets_path: pkg/rpm/scriptlets.toml

  no_docker:
    uses: NLnetLabs/.github/.github/workflows/pkg-rust.yml@v1.1.0
    with:
      cross_build_rules_path: pkg/rules/cross-build-rules.yml
      package_build_rules_path: pkg/rules/package-build-rules.yml
      package_test_rules_path: pkg/rules/package-test-rules.yml
      package_test_scripts_path: pkg/test-scripts/test-<package>.sh

      cross_build_args: --no-default-features
      deb_extra_build_packages: libssl-dev
      deb_maintainer: The NLnet Labs RPKI Team <rpki@nlnetlabs.nl>
      rpm_scriptlets_path: pkg/rpm/scriptlets.toml

  only_docker:
    uses: NLnetLabs/.github/.github/workflows/pkg-rust.yml@v1.1.0
    secrets: inherit
    with:
      docker_org: ximoneighteen
      docker_repo: ximontest

      cross_build_rules_path: pkg/rules/cross-build-rules.yml
      docker_build_rules_path: pkg/rules/docker-build-rules.yml

      cross_build_args: --no-default-features

  no_cross:
    uses: NLnetLabs/.github/.github/workflows/pkg-rust.yml@v1.1.0
    secrets: inherit
    with:
      docker_org: ximoneighteen
      docker_repo: ximontest

      docker_build_rules_path: pkg/rules/docker-build-rules-no-cross.yml
      package_build_rules_path: pkg/rules/package-build-rules-no-cross.yml
      package_test_rules_path: pkg/rules/package-test-rules-no-cross.yml
      package_test_scripts_path: pkg/test-scripts/test-<package>.sh

      deb_extra_build_packages: libssl-dev
      deb_maintainer: The NLnet Labs RPKI Team <rpki@nlnetlabs.nl>
      rpm_scriptlets_path: pkg/rpm/scriptlets.toml
