name: Packaging

on:
  push:
    branches:
      - main
    tags:
      - v*

# Triggering on PRs and arbitrary branch pushes is not enabled because most of the time only the CI build should be
  # triggered, not the packaging build. In cases where you want to test changes to this workflow this trigger enables
  # you to manually invoke this workflow on an arbitrary branch as needed.
  workflow_dispatch:

defaults:
  run:
    # see: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell
    shell: bash --noprofile --norc -eo pipefail -x {0}

jobs:
  package:
    uses: ximon18/.github/.github/workflows/pkg.yml@main
    secrets: inherit
    with:
      docker_org: ximoneighteen
      docker_repo: ximontest

      cross_build_rules_path: pkg/rules/cross-targets.yml
      docker_build_rules_path: pkg/rules/docker-images-to-build.yml
      pkg_build_rules_path: pkg/rules/packages-to-build.yml
      pkg_test_rules_path: pkg/rules/packages-to-test.yml
      pkg_test_scripts_path: pkg/test-scripts/test-<package>.sh

      cross_build_args: --no-default-features
      deb_extra_build_packages: libssl-dev
      deb_maintainer: The NLnet Labs RPKI Team <rpki@nlnetlabs.nl>
      rpm_extra_build_packages: openssl-devel
