name: Packaging

on:
  push:
  workflow_dispatch:

# TODO: Use a matrix here for the different permutations of settings to invoke the reusable workflow with?

jobs:
  full:
    uses: NLnetLabs/.github/.github/workflows/pkg-rust.yml@v3.0.4
    secrets: inherit
    with:
      cross_build_rules: pkg/rules/cross-build-rules.yml
      cross_build_args: --no-default-features

      docker_org: ximoneighteen
      docker_repo: ximontest
      docker_build_rules: pkg/rules/docker-build-rules.yml

      package_build_rules: |
        pkg:
          - "mytest"
        image:
          - "ubuntu:jammy" # ubuntu/22.04
          - "debian:stretch"
          - 'centos:7'
          - 'rockylinux:8'     # compatible with EOL centos:8
        target:
          - "x86_64"
        include:
          # package for the Raspberry Pi 1b as an ARMv6 cross compiled variant of the Debian Buster upon which
          # Raspbian 10 is based.
          - pkg: "mytest"
            image: "debian:buster"
            target: "arm-unknown-linux-gnueabihf"

          - pkg: "mytest"
            image: "centos:7"
            systemd_service_unit_file: "pkg/common/mytest.mytest.*"
            target: "x86_64"

          # CentOS 8 became EOL and is in theory still usable as a build container as there is still a Docker image
          # available, and package installation can be done by switching the yum config in the container to use packages
          # from the CentOS 8 vault rather than the now offline actual CentOS 8 repository. However, due to experiencing
          # lots of timed out connections to the vault we will build the CentOS 8 compatible package in a Rocky Linux
          # container instead, as Rocky Linux is 100% compatible with CentOS 8. The server at packages.nlnetlabs.nl
          # however has a repo for CentOS 8, not Rocky Linux, and determines the repo to publish in based on the name of
          # the archive that we produce below which is in turn based by default on the container image used to build. We
          # therefore in this case need to specify that the O/S we are building for has a different name than the Docker
          # image we are building it in.
          - pkg: "mytest"
            image: 'rockylinux:8'
            systemd_service_unit_file: "pkg/common/mytest.mytest.*"
            target: "x86_64"
            os: 'centos:8'

      package_test_rules: pkg/rules/package-test-rules.yml
      package_test_scripts_path: pkg/test-scripts/test-<package>.sh

      deb_extra_build_packages: libssl-dev
      deb_maintainer: The NLnet Labs RPKI Team <rpki@nlnetlabs.nl>
      deb_apt_key_url: 'https://raw.githubusercontent.com/NLnetLabs/.github-testing/repo-test/repo/apt-key.asc'
      deb_apt_source: 'deb https://raw.githubusercontent.com/NLnetLabs/.github-testing/repo-test/repo/linux/${OS_NAME}/ ${OS_REL} main'

      rpm_scriptlets_path: pkg/rpm/scriptlets.toml
      rpm_yum_key_url: 'https://raw.githubusercontent.com/NLnetLabs/.github-testing/repo-test/repo/yum-key.asc'
      rpm_yum_repo: |
        [nlnetlabs]
        name=NLnet Labs
        baseurl=https://raw.githubusercontent.com/NLnetLabs/.github-testing/repo-test/repo/linux/centos/$releasever/main/$basearch
        enabled=1

  check_full:
    runs-on: ubuntu-latest
    needs: full
    steps:
      - name: Check Docker image publication
        if: ${{ (contains(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main') && !needs.full.outputs.docker_images_published }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed("Expected Docker images to have been published but output `docker_images_published` is false")

      - name: Check Docker manifest publication
        if: ${{ (contains(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main') !needs.full.outputs.docker_manifest_published }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed("Expected Docker manifest to have been published but output `docker_manifest_published` is false")

  minimal:
    uses: NLnetLabs/.github/.github/workflows/pkg-rust.yml@v3.0.4

  no_test_scripts:
    uses: NLnetLabs/.github/.github/workflows/pkg-rust.yml@v3.0.4
    secrets: inherit
    with:
      cross_build_args: --no-default-features

      docker_org: ximoneighteen
      docker_repo: ximontest
      docker_build_rules: pkg/rules/docker-build-rules.yml

      package_build_rules: pkg/rules/package-build-rules.yml
      package_test_rules: pkg/rules/package-test-rules.yml

      deb_extra_build_packages: libssl-dev
      deb_maintainer: The NLnet Labs RPKI Team <rpki@nlnetlabs.nl>
      deb_apt_key_url: 'https://raw.githubusercontent.com/NLnetLabs/.github-testing/repo-test/repo/apt-key.asc'
      deb_apt_source: 'deb https://raw.githubusercontent.com/NLnetLabs/.github-testing/repo-test/repo/linux/${OS_NAME}/ ${OS_REL} main'

      rpm_scriptlets_path: pkg/rpm/scriptlets.toml
      rpm_yum_key_url: 'https://raw.githubusercontent.com/NLnetLabs/.github-testing/repo-test/repo/yum-key.asc'
      rpm_yum_repo: |
        [nlnetlabs]
        name=NLnet Labs
        baseurl=https://raw.githubusercontent.com/NLnetLabs/.github-testing/repo-test/repo/linux/centos/$releasever/main/$basearch
        enabled=1

  no_tests:
    uses: NLnetLabs/.github/.github/workflows/pkg-rust.yml@v3.0.4
    secrets: inherit
    with:
      cross_build_args: --no-default-features

      docker_org: ximoneighteen
      docker_repo: ximontest
      docker_build_rules: pkg/rules/docker-build-rules.yml

      package_build_rules: pkg/rules/package-build-rules.yml
      package_test_scripts_path: pkg/test-scripts/test-<package>.sh

      deb_extra_build_packages: libssl-dev
      deb_maintainer: The NLnet Labs RPKI Team <rpki@nlnetlabs.nl>
      deb_apt_key_url: 'https://raw.githubusercontent.com/NLnetLabs/.github-testing/repo-test/repo/apt-key.asc'
      deb_apt_source: 'deb https://raw.githubusercontent.com/NLnetLabs/.github-testing/repo-test/repo/linux/${OS_NAME}/ ${OS_REL} main'

      rpm_scriptlets_path: pkg/rpm/scriptlets.toml
      rpm_yum_key_url: 'https://raw.githubusercontent.com/NLnetLabs/.github-testing/repo-test/repo/yum-key.asc'
      rpm_yum_repo: |
        [nlnetlabs]
        name=NLnet Labs
        baseurl=https://raw.githubusercontent.com/NLnetLabs/.github-testing/repo-test/repo/linux/centos/$releasever/main/$basearch
        enabled=1

  no_docker:
    uses: NLnetLabs/.github/.github/workflows/pkg-rust.yml@v3.0.4
    with:
      cross_build_args: --no-default-features

      package_build_rules: pkg/rules/package-build-rules.yml
      package_test_rules: pkg/rules/package-test-rules.yml
      package_test_scripts_path: pkg/test-scripts/test-<package>.sh

      deb_extra_build_packages: libssl-dev
      deb_maintainer: The NLnet Labs RPKI Team <rpki@nlnetlabs.nl>
      deb_apt_key_url: 'https://raw.githubusercontent.com/NLnetLabs/.github-testing/repo-test/repo/apt-key.asc'
      deb_apt_source: 'deb https://raw.githubusercontent.com/NLnetLabs/.github-testing/repo-test/repo/linux/${OS_NAME}/ ${OS_REL} main'

      rpm_scriptlets_path: pkg/rpm/scriptlets.toml
      rpm_yum_key_url: 'https://raw.githubusercontent.com/NLnetLabs/.github-testing/repo-test/repo/yum-key.asc'
      rpm_yum_repo: |
        [nlnetlabs]
        name=NLnet Labs
        baseurl=https://raw.githubusercontent.com/NLnetLabs/.github-testing/repo-test/repo/linux/centos/$releasever/main/$basearch
        enabled=1

  only_docker:
    uses: NLnetLabs/.github/.github/workflows/pkg-rust.yml@v3.0.4
    secrets: inherit
    with:
      cross_build_args: --no-default-features

      docker_org: ximoneighteen
      docker_repo: ximontest
      docker_build_rules: pkg/rules/docker-build-rules.yml

  docker_no_secrets:
    uses: NLnetLabs/.github/.github/workflows/pkg-rust.yml@v3.0.4
    with:
      docker_org: ximoneighteen
      docker_repo: ximontest
      docker_build_rules: |
        platform: ["linux/amd64"]
        shortname: ["amd64"]
        mode: ["build"]

  check_only_docker:
    runs-on: ubuntu-latest
    needs: only_docker
    steps:
      - name: Check Docker image publication
        if: ${{ (contains(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main') && !needs.only_docker.outputs.docker_images_published }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed("Expected Docker images to have been published but output `docker_images_published` is false")

      - name: Check Docker manifest publication
        if: ${{ (contains(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main') !needs.only_docker.outputs.docker_manifest_published }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed("Expected Docker manifest to have been published but output `docker_manifest_published` is false")

  no_cross:
    uses: NLnetLabs/.github/.github/workflows/pkg-rust.yml@v3.0.4
    secrets: inherit
    with:
      docker_org: ximoneighteen
      docker_repo: ximontest
      docker_build_rules: pkg/rules/docker-build-rules-no-cross.yml

      package_build_rules: pkg/rules/package-build-rules-no-cross.yml
      package_test_rules: pkg/rules/package-test-rules-no-cross.yml
      package_test_scripts_path: pkg/test-scripts/test-<package>.sh

      deb_extra_build_packages: libssl-dev
      deb_maintainer: The NLnet Labs RPKI Team <rpki@nlnetlabs.nl>
      deb_apt_key_url: 'https://raw.githubusercontent.com/NLnetLabs/.github-testing/repo-test/repo/apt-key.asc'
      deb_apt_source: 'deb https://raw.githubusercontent.com/NLnetLabs/.github-testing/repo-test/repo/linux/${OS_NAME}/ ${OS_REL} main'

      rpm_scriptlets_path: pkg/rpm/scriptlets.toml
      rpm_yum_key_url: 'https://raw.githubusercontent.com/NLnetLabs/.github-testing/repo-test/repo/yum-key.asc'
      rpm_yum_repo: |
        [nlnetlabs]
        name=NLnet Labs
        baseurl=https://raw.githubusercontent.com/NLnetLabs/.github-testing/repo-test/repo/linux/centos/$releasever/main/$basearch
        enabled=1

  check_no_cross:
    runs-on: ubuntu-latest
    needs: no_cross
    steps:
      - name: Check Docker image publication
        if: ${{ (contains(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main') && !needs.no_cross.outputs.docker_images_published }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed("Expected Docker images to have been published but output `docker_images_published` is false")

      - name: Check Docker manifest publication
        if: ${{ (contains(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main') && !needs.no_cross.outputs.docker_manifest_published }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed("Expected Docker manifest to have been published but output `docker_manifest_published` is false")
