name: Packaging

on:
  push:
  workflow_dispatch:

# TODO: Use a matrix here for the different permutations of settings to invoke the reusable workflow with?

jobs:
  no_cross:
    uses: NLnetLabs/.github/.github/workflows/pkg-rust.yml@job-summaries-test
    secrets: inherit
    with:
      docker_org: ximoneighteen
      docker_repo: ximontest
      docker_build_rules_path: pkg/rules/docker-images-to-build-no-cross.yml
