name: Packaging

on:
  push:
  workflow_dispatch:

env:
  REUSABLE_WORKFLOW_VER: fix_docker_is_required

# TODO: Use a matrix here for the different permutations of settings to invoke the reusable workflow with?

jobs:
  package:
    uses: NLnetLabs/.github/.github/workflows/pkg-rust.yml@${{ env.REUSABLE_WORKFLOW_VER }}
    secrets: inherit
    with:
      docker_org: ximoneighteen
      docker_repo: ximontest

      cross_build_rules_path: pkg/rules/cross-targets.yml
      docker_build_rules_path: pkg/rules/docker-images-to-build.yml
      package_build_rules_path: pkg/rules/packages-to-build.yml
      package_test_rules_path: pkg/rules/packages-to-test.yml
      package_test_scripts_path: pkg/test-scripts/test-<package>.sh

      cross_build_args: --no-default-features
      deb_extra_build_packages: libssl-dev
      deb_maintainer: The NLnet Labs RPKI Team <rpki@nlnetlabs.nl>
      rpm_extra_build_packages: openssl-devel

  package_without_docker:
    uses: NLnetLabs/.github/.github/workflows/pkg-rust.yml@${{ env.REUSABLE_WORKFLOW_VER }}
    with:
      cross_build_rules_path: pkg/rules/cross-targets.yml
      docker_build_rules_path: pkg/rules/docker-images-to-build.yml
      package_build_rules_path: pkg/rules/packages-to-build.yml
      package_test_rules_path: pkg/rules/packages-to-test.yml
      package_test_scripts_path: pkg/test-scripts/test-<package>.sh

      cross_build_args: --no-default-features
      deb_extra_build_packages: libssl-dev
      deb_maintainer: The NLnet Labs RPKI Team <rpki@nlnetlabs.nl>
      rpm_extra_build_packages: openssl-devel
