name: Packaging

on:
  push:

  workflow_dispatch:

  schedule:
    - cron: '0 0 * * 0'

# TODO: Use a matrix here for the different permutations of settings to invoke the reusable workflow with?

jobs:
  test_with_alt_cargo_toml:
    uses: NLnetLabs/ploutos/.github/workflows/pkg-rust.yml@v7.1.2
    secrets: inherit
    with:
      artifact_prefix: test_with_alt_cargo_toml
      manifest_dir: virtual
      workspace_package: app

      package_build_rules: |
        pkg:
          - "app"
        image:
          - "rockylinux:8"
          - "ubuntu:jammy"
        mode:
          - "fresh-install"
        target:
          - "x86_64"
